# Non Graded Challenge 5


_Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra._

---


In [2]:
import numpy as np



- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$


In [5]:
tensor = np.array([[[23, 50],[7, 12]],[[57, 67],[99, 43]],
                    [[75, 21],[57, 12]],[[87, 26],[18,14]]])
print(tensor.shape)

(4, 2, 2)



- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$


In [5]:
# Buat matrix
a = np.array([[23,50,19],[7,12,109],[57,67,98]])
b = np.array([17,12,19])
print('a = ', a)
print('b = ', b)

a =  [[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
b =  [17 12 19]


In [6]:
# perkalian matrix menggunakan dot product
a@b

array([1352, 2334, 3635])


- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$



In [7]:
a = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [8]:
# transpose a
a.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [9]:
# hitung determinan a
np.linalg.det(a)

131344.0000000002

In [10]:
# invers a
np.linalg.inv(a)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])